services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    env_file: .env
    ports:
      - '127.0.0.1:${N8N_PORT}:5678'
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
